<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>de8da6a3-df76-443e-9381-cb77c6beeb39</testSuiteGuid>
   <testCaseLink>
      <guid>a3a7ada0-8373-4416-ad3c-e8b8d4338381</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login with valid credentials</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84c3a1e6-5b45-4e9e-a0d3-730acf82390b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34ee0d65-a394-4283-b463-ad3331df797d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d074c378-7429-444c-9917-1b05d42a018a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login/Neg - Login with invalid email format</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71d6840a-c116-49ab-beb2-2109f770f67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8370196d-aa32-4ce8-b23e-5f84c9f6675d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>765fca0e-7d24-4c3f-adee-428090e0b861</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Neg - Login with unregistered email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>533d2f3f-adf0-42dd-bda1-88e244e92d90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53e41a79-8192-4979-9a29-3e5fd959cff6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fa871b6-7706-4203-b0d6-62cb9f59fddd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login/Neg - Login with empty email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32294612-78eb-4fea-9801-e51a86e76a8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44e2d4a7-ba84-4bc4-9d36-d78905bcb2ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ceda48ad-5bc4-418a-af22-cc5c7500ea97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login/Neg - Login with incorrect password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b080d7f-1aa2-4970-8faa-f8c071d5187c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>768c8574-4c2a-4011-a71f-f89868cd1998</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a886a05-dfb0-4da0-979f-68ef049d8d30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login/Neg - Login with empty password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b09ae1d7-41a5-48e6-9249-4d93fae2208d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6929ddb7-c32e-4cfe-821c-e8a3b4f367d2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
